Email-notification Api
Zummit-Africa-Inc/zapi-dummy-notification pull request #1
Opened 2022-06-14 21:25 UTC by Jude-adesulu

1. Created an api to send mail to users using nodemailer as the means of transportation
2. Created an api to verify user email by sending a token
3. created an endpoint to confirm the token

2022-06-15 09:59 UTC, SunmadeBabafemi requested changes

2022-06-15 09:59 UTC, SunmadeBabafemi commented on src/email-confirmation/email-confirmation.controller.ts
> +  async confirmEmail(@Body('token') token: string) {
1. your get request should have the appropriate url that should contain the token...
2. since it is a get request you cannot have a body but rather query params that takes the token from the url and decodes it

2022-06-15 10:06 UTC, SunmadeBabafemi commented on src/email-confirmation/email-confirmation.service.ts
> +        ZuAppResponse.BadRequest('Unauthorized', 'Email not confirmed'),
when using the custom response .. try to always put the appropriate status code.. unauthorized should be 403.. you can include it in the response too

2022-06-15 10:53 UTC, Jude-adesulu commented on src/email-confirmation/email-confirmation.service.ts
> +        ZuAppResponse.BadRequest('Unauthorized', 'Email not confirmed'),
The changes are now made sir, you can review

2022-07-14 09:07 UTC, PhilemonBrain approved these changes

2022-07-14 09:29 UTC, closed without merging